#!/bin/zsh
# This hook is run after every virtualenv is activated.

if [ -n "$ZSH_VERSION" ]; then
    PS1="$_OLD_VIRTUAL_PS1"
    _OLD_RPROMPT="$RPROMPT"
    RPROMPT="%{${fg[green]}%}`basename \"$VIRTUAL_ENV\"`%{${reset_color}%} $RPROMPT"
fi
